// Generated by https://quicktype.io

class ActoresModel { //JSON: "cast"
  int? id;
  String? name;
  String? originalName;
  String? profilePath;
  int? castId;
  String? character;
  int? order;

  ActoresModel({
    this.id,
    this.name,
    this.originalName,
    this.profilePath,
    this.castId,
    this.character,
    this.order,
  });

  factory ActoresModel.fromMap(Map<String,dynamic> map){
    return ActoresModel(
      id                : map['id'],
      name              : map['name'],
      originalName      : map['original_name'],
      profilePath       : map['profile_path'],
      castId            : map['cast_id'], 
      character         : map['character'],
      order             : map['order']
    );
  }
}

