// Generated by https://quicktype.io

class VideoModel {
  String? iso6391;
  String? iso31661;
  String? name;
  String? key;
  String? site;
  int? size;
  String? type;
  String? publishedAt;
  String? id;

  VideoModel({
    this.iso6391,
    this.iso31661,
    this.name,
    this.key,
    this.site,
    this.size,
    this.type,
    this.publishedAt,
    this.id
  });

  factory VideoModel.fromMap(Map<String,dynamic> map){
    return VideoModel(
      iso6391       : map['iso_639_1'],
      iso31661      : map['iso_3166_1'],
      name          : map['name'],
      key           : map['key'],
      site          : map['site'],
      size          : map['size'],
      type          : map['type'],
      publishedAt   : map['published_at'],
      id            : map['id']   
    );
  }
}
